# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    container_name: sonarqube-postgresql-1
    volumes:
      - './postgresql_data:/bitnami/postgresql'

  sonarqube:
    image: docker.io/bitnami/sonarqube:10
    container_name: sonarqube-sonarqube-1
    volumes:
      - './sonarqube_data:/bitnami/sonarqube'
    depends_on:
      - postgresql
    # environment:
    #   SONARQUBE_EXTRA_PROPERTIES: >
    #       sonar.security.realm=LDAP
    #       sonar.authenticator.downcase=true
    #       ldap.url=ldap://localhost:10389
    #       ldap.bindDn=cn=sonar,ou=users,o=mycompany
    #       ldap.bindPassword=secret
    #       ldap.authentication=simple
    #       ldap.user.baseDn=cn=users,dc=example,dc=org
    #       ldap.group.baseDn=cn=groups,dc=example,dc=org